# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  deps:
    docker:
    # specify the version you desire here
      - image: roquie/composer-parallel

    working_directory: ~/repo

    steps:
      - checkout

    # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
          - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
  test:
    docker:
    # specify the version you desire here
      - image: spacetabio/amphp-alpine:7.4-wkhtmltopdf-xdebug-1.0.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      # run static analyse
      - run: vendor/bin/phpstan analyse src --level 6

      # run tests!
      - run: docker-php-ext-install xdebug
      - run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - run: apk add bash
      - run: bash -c "bash <(curl -s https://codecov.io/bash)"

workflows:
  version: 2
  test_app:
    jobs:
      - deps
      - test:
          requires:
            - deps
